### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by timeisflowing** [universal7420/local_manifests#1]
Hi, especially for noblelte, can you share a script that downloads and compiles everything in one script ? 
For example, we just want to compile noblelte..
How can we do this step by step and faster ?

Respects.

**Comment by JoshuaDoes** [comment]
Hey, I might look into this at a later date!

For now, you should follow the LineageOS build environment setup guide for a related device such as star2lte (https://wiki.lineageos.org/devices/star2lte/build) up to and including the "Download the source code" section, but stop after this section finishes! Don't prepare the device specific code from this guide or follow any further steps.

Next, download the `noblelte.xml` file from this repository, then save it to `~/android/lineage/.repo/local_manifests/noblelte.xml` (create the `local_manifests` folder if it doesn't exist yet).

Finally, run `repo sync` again to download the noblelte device sources, then run these commands to build for noblelte:
```
$ source build/envsetup.sh
$ breakfast noblelte
$ brunch noblelte
```

After that finishes, you should have successfully built LineageOS 17.1 for noblelte! This should also apply to the other 8 of 9 device variants we support. If this helped you please close this issue, but if you have further questions please ask so others can look back and find the answer!

**Comment by timeisflowing** [comment]
Thanks, I wish you good work.

> 
> 
> Hey, I might look into this at a later date!
> 
> For now, you should follow the LineageOS build environment setup guide for a related device such as star2lte (https://wiki.lineageos.org/devices/star2lte/build) up to and including the "Download the source code" section, but stop after this section finishes! Don't prepare the device specific code from this guide or follow any further steps.
> 
> Next, download the `noblelte.xml` file from this repository, then save it to `~/android/lineage/.repo/local_manifests/noblelte.xml` (create the `local_manifests` folder if it doesn't exist yet).
> 
> Finally, run `repo sync` again to download the noblelte device sources, then run these commands to build for noblelte:
> 
> ```
> $ source build/envsetup.sh
> $ breakfast noblelte
> $ brunch noblelte
> ```
> 
> After that finishes, you should have successfully built LineageOS 17.1 for noblelte! This should also apply to the other 8 of 9 device variants we support. If this helped you please close this issue, but if you have further questions please ask so others can look back and find the answer!
