### ISSUE TITLE
User-build fails (SELINUX_IGNORE_NEVERALLOWS := true cannot be used in user builds)

### ISSUE THREAD

**Issue by xwopen** [universal7420/local_manifests#2]
brunch noblelte user
FAILED:
system/sepolicy/Android.mk:87: error: SELINUX_IGNORE_NEVERALLOWS := true cannot be used in user builds.

**Comment by JoshuaDoes** [comment]
We don't have a valid sepolicy either, so user builds will always fail. You must run a userdebug or an eng build when using this tree.
